### ISSUE TITLE
支付宝H5容器头部背景色设置不支持

### ISSUE THREAD

**Issue by zhao-zwl** [koubei-fe/feedback#1]
kb.setTitleBar({
      title: '设置TitleBar背景色',
      backgroundColor: '#ED4A4D'
    });

backgroundColor在支付宝H5容器里不起作用

**Comment by yulongheli** [comment]
8月份口碑前端开放迭代会支持。

**Comment by H5DevHoward** [comment]
我在瓢虫上测试结果是：
背景色能设置，但是标题颜色设置不了，你是不是写错了？

**Comment by zhao-zwl** [comment]
1.首次进入的时候设置背景色是可以的，当滚动屏幕的时候再设置就不可以了
2.链接加上?__webview_options__=transparentTitle%3Dalways   在滚动屏幕时设置背景色也不可以
