### ISSUE TITLE
kb.share分享页面修改url和title在支付宝app中不起作用

### ISSUE THREAD

**Issue by VivienYang** [koubei-fe/feedback#2]
var title='xxx';
var content='xxx';
var shareurl='xxx';
kb.share({title:title,content:title,url:shareurl},function(result){
      kb.alert(result.shareResult);
});
分享的url与页面url不一致，用该api修改后没有生效

**Comment by yulongheli** [comment]
新版本支付宝的 share 确实不能用了，我们马上提供一个新的 API。
